"GET /d HTTP/1.1" 500 59
"GET /d HTTP/1.1" 500 59
"GET /d HTTP/1.1" 500 59
"GET /d HTTP/1.1" 500 59
Internal Server Error: /jobs/create/
Traceback (most recent call last):
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\jobs\views.py", line 24, in create_job
    custom_permission_denied()
    ^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'custom_permission_denied' is not defined
"GET /jobs/create/ HTTP/1.1" 500 1034
Internal Server Error: /jobs/create/
Traceback (most recent call last):
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\jobs\views.py", line 24, in create_job
    custom_permission_denied()
    ^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'custom_permission_denied' is not defined
"GET /jobs/create/ HTTP/1.1" 500 1034
Internal Server Error: /
Traceback (most recent call last):
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\src\views.py", line 15, in index
    return render(request, 'index.html', {'jobs': jobs, 'is_teacher': is_teacher})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'home' not found. 'home' is not a valid view function or pattern name.
"GET / HTTP/1.1" 500 1034
Internal Server Error: /
Traceback (most recent call last):
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\src\views.py", line 15, in index
    return render(request, 'index.html', {'jobs': jobs, 'is_teacher': is_teacher})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'home' not found. 'home' is not a valid view function or pattern name.
"GET / HTTP/1.1" 500 1034
"GET /r HTTP/1.1" 500 59
"GET /favicon.ico HTTP/1.1" 500 59
"GET / HTTP/1.1" 500 59
"GET /favicon.ico HTTP/1.1" 500 59
"GET / HTTP/1.1" 500 59
"GET /favicon.ico HTTP/1.1" 500 59
"GET / HTTP/1.1" 500 59
"GET /favicon.ico HTTP/1.1" 500 59
"GET / HTTP/1.1" 500 59
"GET /favicon.ico HTTP/1.1" 500 59
"GET /favicon.ico HTTP/1.1" 500 59
"GET /favicon.ico HTTP/1.1" 500 59
"GET / HTTP/1.1" 500 59
"GET / HTTP/1.1" 500 59
"GET /favicon.ico HTTP/1.1" 500 59
"GET / HTTP/1.1" 500 59
"GET /favicon.ico HTTP/1.1" 500 59
"GET /favicon.ico HTTP/1.1" 500 59
"GET / HTTP/1.1" 500 59
"GET /favicon.ico HTTP/1.1" 500 59
"GET / HTTP/1.1" 500 59
"GET /favicon.ico HTTP/1.1" 500 59
"GET / HTTP/1.1" 500 59
"GET /favicon.ico HTTP/1.1" 500 59
"GET / HTTP/1.1" 500 59
"GET /favicon.ico HTTP/1.1" 500 59
"GET / HTTP/1.1" 500 59
"GET /favicon.ico HTTP/1.1" 500 59
"GET / HTTP/1.1" 500 59
"GET /favicon.ico HTTP/1.1" 500 59
"GET / HTTP/1.1" 500 59
"GET / HTTP/1.1" 500 59
"GET /favicon.ico HTTP/1.1" 500 59
"GET /favicon.ico HTTP/1.1" 500 59
"GET / HTTP/1.1" 500 59
"GET /favicon.ico HTTP/1.1" 500 59
Internal Server Error: /
Traceback (most recent call last):
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\smartif.py", line 180, in translate_token
    op = OPERATORS[token]
         ~~~~~~~~~^^^^^^^
KeyError: "user.groups.filter(name='student').exists()"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\src\views.py", line 15, in index
    return render(request, 'index.html', {'jobs': jobs, 'is_teacher': is_teacher})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\backends\django.py", line 79, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 196, in compile_nodelist
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\defaulttags.py", line 962, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\defaulttags.py", line 862, in do_for
    nodelist_loop = parser.parse(
                    ^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 518, in parse
    raise self.error(token, e)
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 516, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\defaulttags.py", line 961, in do_if
    condition = TemplateIfParser(parser, bits).parse()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\defaulttags.py", line 894, in __init__
    super().__init__(*args, **kwargs)
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\smartif.py", line 171, in __init__
    mapped_tokens.append(self.translate_token(token))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\smartif.py", line 182, in translate_token
    return self.create_var(token)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\defaulttags.py", line 897, in create_var
    return TemplateLiteral(self.template_parser.compile_filter(value), value)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 605, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 706, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '(name='student').exists()' from 'user.groups.filter(name='student').exists()'
"GET / HTTP/1.1" 500 259745
Internal Server Error: /jobs/responses/
Traceback (most recent call last):
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\jobs\views.py", line 79, in view_responses
    applications[job] = job.applications.all()
                        ^^^^^^^^^^^^^^^^
AttributeError: 'Job' object has no attribute 'applications'
"GET /jobs/responses/ HTTP/1.1" 500 70878
Internal Server Error: /jobs/responses/
Traceback (most recent call last):
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\jobs\views.py", line 79, in view_responses
    applications[job] = job.applications.all()
                        ^^^^^^^^^^^^^^^^
AttributeError: 'Job' object has no attribute 'applications'
"GET /jobs/responses/ HTTP/1.1" 500 71143
Internal Server Error: /jobs/responses/
Traceback (most recent call last):
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\jobs\views.py", line 79, in view_responses
    applications[job] = job.applications.all()
                        ^^^^^^^^^^^^^^^^
AttributeError: 'Job' object has no attribute 'applications'
"GET /jobs/responses/ HTTP/1.1" 500 71015
Internal Server Error: /jobs/responses/
Traceback (most recent call last):
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\jobs\views.py", line 79, in view_responses
    applications[job] = job.applications.all()
                        ^^^^^^^^^^^^^^^^
AttributeError: 'Job' object has no attribute 'applications'
"GET /jobs/responses/ HTTP/1.1" 500 71015
Internal Server Error: /jobs/responses/
Traceback (most recent call last):
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\jobs\views.py", line 79, in view_responses
    applications[job] = job.applications.all()
                        ^^^^^^^^^^^^^^^^
AttributeError: 'Job' object has no attribute 'applications'
"GET /jobs/responses/ HTTP/1.1" 500 71015
Internal Server Error: /jobs/responses/
Traceback (most recent call last):
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\jobs\views.py", line 79, in view_responses
    applications[job] = job.applications.all()
                        ^^^^^^^^^^^^^^^^
AttributeError: 'Job' object has no attribute 'applications'
"GET /jobs/responses/ HTTP/1.1" 500 71015
Internal Server Error: /jobs/responses/
Traceback (most recent call last):
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\jobs\views.py", line 79, in view_responses
    applications[job] = job.applications.all()
                        ^^^^^^^^^^^^^^^^
AttributeError: 'Job' object has no attribute 'applications'
"GET /jobs/responses/ HTTP/1.1" 500 71143
Internal Server Error: /
Traceback (most recent call last):
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\db\models\fields\__init__.py", line 2123, in get_prep_value
    return int(value)
           ^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'SimpleLazyObject'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\src\views.py", line 16, in index
    applications = {job.id: job.applications.filter(user=user).exists() for job in jobs}
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\src\views.py", line 16, in <dictcomp>
    applications = {job.id: job.applications.filter(user=user).exists() for job in jobs}
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\db\models\sql\query.py", line 1609, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\db\models\sql\query.py", line 1641, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\db\models\sql\query.py", line 1555, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\db\models\sql\query.py", line 1385, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\db\models\lookups.py", line 30, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\db\models\fields\related_lookups.py", line 156, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\db\models\fields\__init__.py", line 2125, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got <SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x00000193d417d590>>.
"GET / HTTP/1.1" 500 132635
Internal Server Error: /
Traceback (most recent call last):
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\db\models\fields\__init__.py", line 2123, in get_prep_value
    return int(value)
           ^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'SimpleLazyObject'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\src\views.py", line 16, in index
    applications = {job.id: job.applications.filter(user=user).exists() for job in jobs}
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\src\views.py", line 16, in <dictcomp>
    applications = {job.id: job.applications.filter(user=user).exists() for job in jobs}
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\db\models\sql\query.py", line 1609, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\db\models\sql\query.py", line 1641, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\db\models\sql\query.py", line 1555, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\db\models\sql\query.py", line 1385, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\db\models\lookups.py", line 30, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\db\models\fields\related_lookups.py", line 156, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\db\models\fields\__init__.py", line 2125, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got <SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x00000193d4111d90>>.
"GET / HTTP/1.1" 500 132763
Internal Server Error: /
Traceback (most recent call last):
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\db\models\fields\__init__.py", line 2123, in get_prep_value
    return int(value)
           ^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'SimpleLazyObject'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\src\views.py", line 16, in index
    applications = {job.id: job.applications.filter(user=user).exists() for job in jobs}
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\src\views.py", line 16, in <dictcomp>
    applications = {job.id: job.applications.filter(user=user).exists() for job in jobs}
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\db\models\sql\query.py", line 1609, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\db\models\sql\query.py", line 1641, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\db\models\sql\query.py", line 1555, in build_filter
    condition = self.build_lookup(lookups, col, value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\db\models\sql\query.py", line 1385, in build_lookup
    lookup = lookup_class(lhs, rhs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\db\models\lookups.py", line 30, in __init__
    self.rhs = self.get_prep_lookup()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\db\models\fields\related_lookups.py", line 156, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\db\models\fields\__init__.py", line 2125, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got <SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x00000193d40ff810>>.
"GET / HTTP/1.1" 500 132635
"POST /jobs/apply/14/ HTTP/1.1" 500 87029
"POST /jobs/apply/14/ HTTP/1.1" 500 87347
Internal Server Error: /jobs/responses/
Traceback (most recent call last):
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\jobs\views.py", line 80, in view_responses
    if job.creator != request.user:
       ^^^
UnboundLocalError: cannot access local variable 'job' where it is not associated with a value
"GET /jobs/responses/ HTTP/1.1" 500 71383
Internal Server Error: /jobs/responses/
Traceback (most recent call last):
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\jobs\views.py", line 80, in view_responses
    if job.creator != request.user:
       ^^^
UnboundLocalError: cannot access local variable 'job' where it is not associated with a value
"GET /jobs/responses/ HTTP/1.1" 500 71118
Internal Server Error: /jobs/responses/
Traceback (most recent call last):
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\jobs\views.py", line 80, in view_responses
    if job.creator != request.user:
       ^^^
UnboundLocalError: cannot access local variable 'job' where it is not associated with a value
"GET /jobs/responses/ HTTP/1.1" 500 71255
Internal Server Error: /jobs/responses/
Traceback (most recent call last):
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\jobs\views.py", line 80, in view_responses
    if job.creator != request.user:
       ^^^
UnboundLocalError: cannot access local variable 'job' where it is not associated with a value
"GET /jobs/responses/ HTTP/1.1" 500 71383
Internal Server Error: /jobs/responses/
Traceback (most recent call last):
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\jobs\views.py", line 80, in view_responses
    if job.creator != request.user:
       ^^^
UnboundLocalError: cannot access local variable 'job' where it is not associated with a value
"GET /jobs/responses/ HTTP/1.1" 500 71118
Internal Server Error: /jobs/responses/
Traceback (most recent call last):
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\jobs\views.py", line 80, in view_responses
    if job.creator != request.user:
       ^^^
UnboundLocalError: cannot access local variable 'job' where it is not associated with a value
"GET /jobs/responses/ HTTP/1.1" 500 71118
Internal Server Error: /jobs/responses/
Traceback (most recent call last):
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: view_responses() missing 1 required positional argument: 'job_id'
"GET /jobs/responses/ HTTP/1.1" 500 67314
Internal Server Error: /
Traceback (most recent call last):
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\src\views.py", line 23, in index
    return render(request, 'index.html', {'jobs': jobs, 'is_teacher': is_teacher, 'is_student': is_student, 'applications': applications,})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\defaulttags.py", line 327, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'view_responses' with no arguments not found. 1 pattern(s) tried: ['jobs/responses/(?P<job_id>[0-9]+)/\\Z']
"GET / HTTP/1.1" 500 193757
Internal Server Error: /
Traceback (most recent call last):
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\src\views.py", line 23, in index
    return render(request, 'index.html', {'jobs': jobs, 'is_teacher': is_teacher, 'is_student': is_student, 'applications': applications,})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\defaulttags.py", line 327, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'view_responses' with no arguments not found. 1 pattern(s) tried: ['jobs/responses/(?P<job_id>[0-9]+)/\\Z']
"GET / HTTP/1.1" 500 193757
Internal Server Error: /
Traceback (most recent call last):
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\src\views.py", line 23, in index
    return render(request, 'index.html', {'jobs': jobs, 'is_teacher': is_teacher, 'is_student': is_student, 'applications': applications,})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\defaulttags.py", line 327, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'view_responses' with arguments '('',)' not found. 1 pattern(s) tried: ['jobs/responses/(?P<job_id>[0-9]+)/\\Z']
"GET / HTTP/1.1" 500 195305
Internal Server Error: /
Traceback (most recent call last):
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\src\views.py", line 23, in index
    return render(request, 'index.html', {'jobs': jobs, 'is_teacher': is_teacher, 'is_student': is_student, 'applications': applications,})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\defaulttags.py", line 327, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'view_responses' with arguments '('',)' not found. 1 pattern(s) tried: ['jobs/responses/(?P<job_id>[0-9]+)/\\Z']
"GET / HTTP/1.1" 500 195305
Internal Server Error: /
Traceback (most recent call last):
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\src\views.py", line 23, in index
    return render(request, 'index.html', {'jobs': jobs, 'is_teacher': is_teacher, 'is_student': is_student, 'applications': applications,})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\defaulttags.py", line 327, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'view_responses' with arguments '('',)' not found. 1 pattern(s) tried: ['jobs/responses/(?P<job_id>[0-9]+)/\\Z']
"GET / HTTP/1.1" 500 195305
Internal Server Error: /
Traceback (most recent call last):
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\src\views.py", line 23, in index
    return render(request, 'index.html', {'jobs': jobs, 'is_teacher': is_teacher, 'is_student': is_student, 'applications': applications,})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\defaulttags.py", line 327, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'view_responses' with arguments '('',)' not found. 1 pattern(s) tried: ['jobs/responses/(?P<job_id>[0-9]+)/\\Z']
"GET / HTTP/1.1" 500 195305
Internal Server Error: /
Traceback (most recent call last):
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\src\views.py", line 23, in index
    return render(request, 'index.html', {'jobs': jobs, 'is_teacher': is_teacher, 'is_student': is_student, 'applications': applications,})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\backends\django.py", line 107, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\defaulttags.py", line 327, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 1008, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 1008, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\base.py", line 969, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\template\defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'view_responses' with arguments '('',)' not found. 1 pattern(s) tried: ['jobs/responses/(?P<job_id>[0-9]+)/\\Z']
"GET / HTTP/1.1" 500 195305
Internal Server Error: /jobs/responses/
Traceback (most recent call last):
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: view_responses() missing 1 required positional argument: 'job_id'
"GET /jobs/responses/ HTTP/1.1" 500 67314
Internal Server Error: /jobs/responses/
Traceback (most recent call last):
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: view_responses() missing 1 required positional argument: 'job_id'
"GET /jobs/responses/ HTTP/1.1" 500 67451
Internal Server Error: /jobs/responses/
Traceback (most recent call last):
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: view_responses() missing 1 required positional argument: 'job_id'
"GET /jobs/responses/ HTTP/1.1" 500 67314
Internal Server Error: /jobs/responses/
Traceback (most recent call last):
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: view_responses() missing 1 required positional argument: 'job_id'
"GET /jobs/responses/ HTTP/1.1" 500 67451
Internal Server Error: /jobs/responses/
Traceback (most recent call last):
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: view_responses() missing 1 required positional argument: 'job_id'
"GET /jobs/responses/ HTTP/1.1" 500 67314
Internal Server Error: /jobs/responses/
Traceback (most recent call last):
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\jobs\views.py", line 84, in view_responses
    for job in jobs:
               ^^^^
NameError: name 'jobs' is not defined
"GET /jobs/responses/ HTTP/1.1" 500 70850
Internal Server Error: /jobs/responses/
Traceback (most recent call last):
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\.venv\lib\python3.11\site-packages\django\contrib\auth\decorators.py", line 60, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\programming\python\DjangoPr2\pp\jobs\views.py", line 79, in view_responses
    raise Exception("This is a test 500 error.")
Exception: This is a test 500 error.
"GET /jobs/responses/ HTTP/1.1" 500 70746
